version: 2
jobs:
  build:
    docker:
      - image: mhazy/dockubercle:latest
    steps:
      - checkout
      - run:
          name: Login to Docker hub
          command: |
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      - run:
          name: Build deployment image
          command: |
            docker build -t mhazy/nodetest:latest .
      - run:
          name: Push image to registry
          command: |
            docker push mhazy/nodetest:latest
      - run:
          name: Setup Kubectl configuration
          command: |
            kops export kubecfg --state s3://cluster_aldodev_state_store aldodevcluster.rangleapp.io
      - run:
          name: Deploy application to cluster
          command: |
            kubectl apply -f ./deployment.yaml