version: 2
jobs:
  build:
    docker:
      - image: mhazy/dockubercle:latest
    steps:
      - setup-docker-engine
      - checkout
      - run:
          name: Build and push image
          command: |
            docker build -t mhazy/nodetest:latest .
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            docker push mhazy/nodetest:latest
      - run:
          name: Setup Kubectl configuration
          command: |
            kops export kubecfg --state s3://cluster_aldodev_state_store aldodevcluster.rangleapp.io
      - run:
          name: Deploy application to cluster
          command: |
            kubectl apply -f ./deployment.yaml