version: 2
jobs:
  build:
    docker:
      - image: mhazy/dockubercle:latest
    steps:
      - setup-docker-engine
      - checkout
      - run:
          name: Build and push image
          command: |
            docker build -t mhazy/nodetest:${CIRCLE_SHA1} .
            docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD}
            docker push mhazy/nodetest:${CIRCLE_SHA1}
      - run:
          name: Setup Kubectl configuration
          command: |
            kops export kubecfg --state s3://cluster_aldodev_state_store aldodevcluster.rangleapp.io
      - run:
          name: Deploy application to cluster
          command: |
            # Temporary replacement before proper templated deployment files
            sed -ie "s/IMAGE_HASH/${CIRCLE_SHA1}/g" ./deployment.yaml
            kubectl delete -f ./deployment.yaml --ignore-not-found=true
            kubectl apply -f ./deployment.yaml
